import Head from 'next/head';
import React, { useRef, useState } from 'react';
import '../styles/Home.module.scss';
import { Canvas, useFrame } from '@react-three/fiber';
import { softShadows, MeshWobbleMaterial, OrbitControls } from '@react-three/drei';
// import { useSpring, a } from 'react-spring/three';

softShadows()

const SpinningMesh = ({ position, args, color, speed }) => {

  // const [expand, setExpand] = useState(false);

  // const props = useSpring({
  //   scale: expand ? [1.4, 1.4, 1.4] : [1, 1, 1],
  // });

  const mesh = useRef(null);

  useFrame(() => (mesh.current.rotation.x = mesh.current.rotation.y += 0.01));

  // onClick={() => setExpand(!expand)} scale={props.scale}

  return (
    <mesh castShadow position={position} ref={mesh}>
      <boxBufferGeometry attach="geometry" args={args} />
      <MeshWobbleMaterial attach='material' color={color} speed={speed} factor={.6} />
    </mesh>
  );
}

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
